config/routes.rb
# encoding: utf-8
#
# Redmine plugin for provides a resubmission tool for issues
#
# Copyright © 2018-2020 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

RedmineApp::Application.routes.draw do	
  match 'test_resubmission_rule' => "resubmissions#test_resubmission_rule", :via => :put
  match 'calc_resubmissions' => "resubmissions#calc_resubmissions", :as => "calc_resubmissions", :via => :get
end

app/controllers/resubmissions_controller.rb
# encoding: utf-8
#
# Redmine plugin for provides a resubmission tool for issues
#
# Copyright © 2018-2020 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

class ResubmissionsController < ApplicationController
  
  unloadable
  
  before_action :authorize_global
  
  # ------------------------------------------------------------------------------------ #
  def test_resubmission_rule 
  
    @startdate           = Date.parse(params[:startdate]) rescue Date.today 
    @new_date, @new_rule = RedmineAutoResubmission.calcfuturedate( @startdate, params[:rule] )
    @feedback_tag        = params[:feedback_tag]
    
    respond_to do |format|
      format.js   { } # renders calc_date.js.erb
    end
    
  rescue Exception => e 
    flash[:error] = e.message
    redirect_back_or_default plugin_settings_path("redmine_auto_resubmission")
  end #def
  
  # ------------------------------------------------------------------------------------ #
  def calc_resubmissions
    
    num = RedmineAutoResubmission.calc_all_resubmission_dates
    flash[:notice] = l(:text_successful_resubmission, :num => num )
    redirect_back_or_default plugin_settings_path("redmine_auto_resubmission")
    
  rescue Exception => e
  
    Rails.logger.info e.message
    Rails.logger.info e.backtrace.join("\n")
    
    flash[:error] = e.message
    redirect_back_or_default plugin_settings_path("redmine_auto_resubmission")
  end #def
  
end #class

app/views/redmine_auto_resubmission/_auto_resubmission_settings.html.erb
<%- issue_date_custom_fields = IssueCustomField.where(:field_format => 'date') %>
<%- issue_rule_custom_fields = IssueCustomField.where(:field_format => ['string', 'list'])  %>
<%- issue_statuses           = IssueStatus.where("is_closed = #{Issue.connection.quoted_false}") %>

<div style="margin-top:10px;"></div>
<fieldset ><legend><%= l(:label_configure_resubmission_fields)%></legend>
  
  <p>
    <%= label_tag( 'settings[custom_field_id_rule]', l(:label_setting_custom_field_id_rule)) %>
    <%= select_tag('settings[custom_field_id_rule]', options_for_select([['', 0]] + issue_rule_custom_fields.collect{|c| [c.name, c.id]}, (@settings['custom_field_id_rule'] || 0))) %>
  </p>
  
  <p>
    <%= label_tag( 'settings[custom_field_id_date]', l(:label_setting_custom_field_id_date)) %>
    <%= select_tag('settings[custom_field_id_date]', options_for_select([['', 0]] + issue_date_custom_fields.collect{|c| [c.name, c.id]}, (@settings['custom_field_id_date'] || 0))) %>
  </p>
  
  <p>
    <%= label_tag( 'settings[open_issues_only]', l(:label_setting_open_issues_only)) %>
    <%= check_box_tag( 'settings[open_issues_only]', '1', settings['open_issues_only'] == '1') %>
  </p>
  
  <p>
    <%= label_tag( 'settings[issue_resubmit_status_id]', l(:label_setting_resubmit_with_issue_status_id)) %>
    <%= select_tag('settings[issue_resubmit_status_id]', options_for_select([['', 0]] + issue_statuses.collect{|c| [c.name, c.id]}, (@settings['issue_resubmit_status_id'] || 0))) %>
  </p>
  
  <p>
    <%= label_tag(    'settings[resubmission_notice]', l(:label_resubmission_notice)) %>
    <%= text_area_tag('settings[resubmission_notice]',  @settings['resubmission_notice'], :cols => 20 ) %>
  </p>
  
</fieldset>

<div style="margin-top:10px;"></div>
<fieldset ><legend><%= l(:label_configure_extend_start_date_fields)%></legend>
  <p>
    <%= label_tag( 'settings[custom_field_id_start_date_rule]', l(:label_setting_custom_field_id_start_date_rule)) %>
    <%= select_tag('settings[custom_field_id_start_date_rule]', options_for_select([['', 0]] + issue_rule_custom_fields.collect{|c| [c.name, c.id]}, (@settings['custom_field_id_start_date_rule'] || 0))) %>
  </p>
</fieldset>

<div style="margin-top:10px;"></div>
<fieldset ><legend><%= l(:label_configure_extend_due_date_fields)%></legend>
  <p>
    <%= label_tag( 'settings[custom_field_id_due_date_rule]', l(:label_setting_custom_field_id_due_date_rule)) %>
    <%= select_tag('settings[custom_field_id_due_date_rule]', options_for_select([['', 0]] + issue_rule_custom_fields.collect{|c| [c.name, c.id]}, (@settings['custom_field_id_due_date_rule'] || 0))) %>
  </p>
</fieldset>
  
<div style="margin-top:10px;"></div>
<fieldset><legend><%= l(:label_test_resubmission_rule)%></legend>

  <p>
    <label><%= l(:label_input_start_date) %></label><%= text_field_tag :startdate %>
  </p>
  <p>
    <label><%= l(:label_input_resubmission_rule) %></label><%= text_field_tag :rule %>
  </p>
  <p>
    <%= link_to l(:label_test_resubmission_rule), "#",
                :remote => true,
                :onclick => "testresubmissionrule('#{url_for(:controller => 'resubmissions', :action => 'test_resubmission_rule', :feedback_tag => 'testresubmissionrule_area', :user_id => User.current.id.to_s)}', $( this ).parents('form'))",
                :class => "" %>
  </p>
    
  <div id="testresubmissionrule_area">&nbsp;</div>
  
  <%= toggle_link l(:label_help), 'redmine_auto_resubmission_help' %>
  
  <span id="redmine_auto_resubmission_help" style="display:none;">
    <%= render "redmine_auto_resubmission/help/help_rule_field_#{I18n.locale}" rescue render 'redmine_auto_resubmission/help/help_rule_field_en' %>
    <%= render "redmine_auto_resubmission/help/help_date_field_#{I18n.locale}" rescue render 'redmine_auto_resubmission/help/help_date_field_en' %>
    <%= render "redmine_auto_resubmission/help/help_status_id_field_#{I18n.locale}" rescue render 'redmine_auto_resubmission/help/help_status_id_field_en' %>
    <%= render "redmine_auto_resubmission/help/help_text_field_#{I18n.locale}" rescue render 'redmine_auto_resubmission/help/help_text_field_en' %>
    <%= render "redmine_auto_resubmission/help/help_start_date_rule_field_#{I18n.locale}" rescue render 'redmine_auto_resubmission/help/help_start_date_rule_field_en' %>
    <%= render "redmine_auto_resubmission/help/help_due_date_rule_field_#{I18n.locale}" rescue render 'redmine_auto_resubmission/help/help_due_date_rule_field_en' %>
  </span>
</fieldset>

<div style="margin-top:10px;"></div>
<fieldset><legend><%= l(:label_calc_resubmissions)%></legend>
  <p>
  <%= link_to l(:button_recalculate), calc_resubmissions_path,
                      :data => {:confirm => l(:text_are_you_sure)},
                      :method => :get,
                      :title => l(:button_recalculate) %>
  </p>
</fieldset>


<script type="text/javascript" charset="utf-8">

function testresubmissionrule(url, form) {
  if(form.value=='') 
    return;
  $.ajax({
    url: url,
    type: 'put',
    data: $(form).serialize()
  });
}
</script>

app/views/redmine_auto_resubmission/_help_rule_field_de.html.erb
<h3>Feld für Wiedervorlage-Regel</h3>

<p>Dieses benutzerdefinierte Feld sollte ein Text-Feld oder eine Drop-Down-Liste für 
ausgewählte <strong>Wiedervorlage-Regeln</strong> zum Berechnen eines neuen 
Wiedervorlage-Datums sein, das immer dann berechnet wird, wenn das aktuelle 
Wiedervorlage-Datum in der Vergangenheit liegt.</p>

<p>
<strong>Vorgeschlagene Werte: &lt;Regel&gt; &lt;Hinweistext&gt; </strong><br />
D1! morgen!<br />
W01! montag!<br />
W1X wöchentlich<br />
W2X zweiwöchentlich<br />
W3X dreiwöchentlich<br />
M1X monatlich<br />
M1F monatlich am 1.<br />
M1M monatlich am 15.<br />
M2L monatlich am letzten Tag<br />
M2X zweimonatlich<br />
M2F zweimonatlich am 1.<br />
M2M zweimonatlich am 15.<br />
M2L zweimonatlich am letzten Tag<br />
M3X dreimonatlich<br />
M3F dreimonatlich am 1.<br />
M3M dreimonatlich am 15.<br />
M3L dreimonatlich am letzten Tag<br />
M6X halbjährlich<br />
M6F halbjährlich am 1.<br />
M6L halbjährlich am letzten<br />
M12X jährlich
</p>

<p>
Der Aufbau der Wiedervorlage-Regel besteht aus drei bis vier Parametern:
</p>

<pre>
1. Parameter: Epochen-Zeichen

 D - steht für Tage, von eng. _D_ays
 W - steht für Wochen, von engl. _W_eeks
 m - steht für Montage, von engl. _m_ondays
 M - steht für Monate, von engl. _M_onths
 q - steht für Quartale, von engl. _q_uarters
 Y - steht für Jahre, von engl. _Y_ears

2. Parameter: Integer

 n - steht für die Anzahl der Epochen

3. Position des Tages in der Epoche (optional) - nur für W, M, Y und q

 F - steht für den ersten Tag der Epoche, von engl. _F_irst, erster des Monats, Montag, 
     erster Tag des Quartals, oder der 01. Januar
 M - steht für den mittigen Tag der Epoche, von engl. _M_id, der 15. des Monats, Mittwoch,
     der 15. der Quartalmitte, oder der 30.Juni
 L - steht für den letzten Tag der Epoche, von engl. _L_ast, letzter Tag des Monats, 
     Freitag (letzter Arbeitstag), letzter Tag des Quartals, oder der 31. Dezember
 W - steht für Wochentag (Montag), wenn der berechnete Tag auf Samstag oder Sonntag fällt
 X - steht für 'keine Korrektur'
 
4. Steuerung der Datumsberechnung

 - - das Zeichen "-" ist das Abbruchszeichen. nach einmaliger Berechnung des neuen Datums 
     wird die Regel gelöscht.
 ! - das Zeichen "!" ist das Zeichen zum Erzwingen eines neuen Datums, obwohl ein Datum in
     dem Widervorlagefeld steht
 * - das Zeichen "*" verhindert das Berechnen eines Datums, wobei "*" aus der Regel 
     gelöscht wird. Notwendig für das Plugin Redmine Attribute-Quickies
     
     Die drei Steuerzeichen müssen in der oben angeführten Reihenfolge vorgegeben werden,
     nämlich - ! *, wobei jede beliebige Untermenge der Zeichen oder auch alle Zeichen 
     ausgelassen werden können.

Beispiel: W1F - eine Woche weiter, erster Tag, also Montag
Beispiel: M3M - drei Monate ab heute, mittiger Tag, also der 15. des Monats
Beispiel: q1- - nächstes Quartal, erster Tag des Quartals, also der 1. Jan., Apr., Jul. 
                oder Okt., nach einmaliger Berechnung wird die Regel gelöscht 
                (Einmalvorlage)               
Beispiel: D1- - morgen, dann Regel löschen
Beispiel: D1-! - morgen!, auch wenn ein anderes Wiedervorlage-Datum bereits notiert ist

Es wird stets ein Datum in der Zukuft berechnet, niemals in der Vergangenheit.
So würde für W0F an einem Freitag (W0 - diese Woche oder 0 Wochen weiter, Montag)
ein Tag in der Vergangenheit berechnet. In diesem Fall wird der nächste Montag berechnet.
So würde für für q0M (q0 - dieses Quartal oder 0 Quartale weiter) die Mitte des Quartals
berechnet, wenn das Quartal fast verstrichen ist. In diesem Fall wird das entsprechende
Datum im nächsten Quartal berechnet

</pre>

app/views/redmine_auto_resubmission/help/_help_date_field_de.html.erb
<h3>Feld für Wiedervorlage-Datum</h3>

<p>Dieses benutzerdefinierte Feld sollte ein Datum-Feld sein.</p>

app/views/redmine_auto_resubmission/help/_help_date_field_en.html.erb
<h3>Field für resubmission-date</h3>

<p>This custom field should be a date field.</p>

app/views/redmine_auto_resubmission/help/_help_due_date_rule_field_de.html.erb
<h3>Feld für Fälligkeitsdatum-Regel</h3>

<p>Dieses benutzerdefinierte Feld sollte ein Text-Feld oder eine Drop-Down-Liste für 
ausgewählte <strong>Fälligkeitsdatum-Regeln</strong> zum Berechnen eines neuen 
Fälligkeitsdatums sein, das immer dann berechnet wird, wenn das aktuelle 
Fälligkeitsdatum in der Vergangenheit liegt.</p>

<p>Dieses Feld kann unkonfiguriert bleiben, um diese Funktion zu deaktivieren</p> 

app/views/redmine_auto_resubmission/help/_help_due_date_rule_field_en.html.erb
<h3>Field for due date rule</h3>

<p>This custom field should be a text field or a drop-down list field for selected 
<strong>due date rules</strong> to calculate a new due date, which is calculated 
if the current due date is a past date</p>

<p>This field may be left unconfigured to deactivate this function</p>

app/views/redmine_auto_resubmission/help/_help_rule_field_de.html.erb
<h3>Feld für Wiedervorlage-Regel</h3>

<p>Dieses benutzerdefinierte Feld sollte ein Text-Feld oder eine Drop-Down-Liste für 
ausgewählte <strong>Wiedervorlage-Regeln</strong> zum Berechnen eines neuen 
Wiedervorlage-Datums sein, das immer dann berechnet wird, wenn das aktuelle 
Wiedervorlage-Datum in der Vergangenheit liegt.</p>

<p>
<strong>Vorgeschlagene Werte: &lt;Regel&gt; &lt;Hinweistext&gt; </strong><br />
D1! morgen!<br />
W01! montag!<br />
W1X wöchentlich<br />
W2X zweiwöchentlich<br />
W3X dreiwöchentlich<br />
M1X monatlich<br />
M1F monatlich am 1.<br />
M1M monatlich am 15.<br />
M2L monatlich am letzten Tag<br />
M2X zweimonatlich<br />
M2F zweimonatlich am 1.<br />
M2M zweimonatlich am 15.<br />
M2L zweimonatlich am letzten Tag<br />
M3X dreimonatlich<br />
M3F dreimonatlich am 1.<br />
M3M dreimonatlich am 15.<br />
M3L dreimonatlich am letzten Tag<br />
M6X halbjährlich<br />
M6F halbjährlich am 1.<br />
M6L halbjährlich am letzten<br />
M12X jährlich
</p>

<p>
Der Aufbau der Wiedervorlage-Regel besteht aus mindestens zwei Parametern:
</p>

<pre>
1. Parameter: Epochen-Zeichen (notwendig)

 D - steht für Tage, von eng. _D_ays
 W - steht für Wochen, von engl. _W_eeks
 m - steht für Montage, von engl. _m_ondays
 M - steht für Monate, von engl. _M_onths
 q - steht für Quartale, von engl. _q_uarters
 Y - steht für Jahre, von engl. _Y_ears

2. Parameter: Integer (notwendig)

 n - steht für die Anzahl der Epochen

3. Position des Tages in der Epoche (optional) - nur für W, M, Y und q

 F - steht für den ersten Tag der Epoche, von engl. _F_irst, erster des Monats, Montag, 
     erster Tag des Quartals, oder der 01. Januar
 M - steht für den mittigen Tag der Epoche, von engl. _M_id, der 15. des Monats, Mittwoch,
     der 15. der Quartalmitte, oder der 30.Juni
 L - steht für den letzten Tag der Epoche, von engl. _L_ast, letzter Tag des Monats, 
     Freitag (letzter Arbeitstag), letzter Tag des Quartals, oder der 31. Dezember
 W - steht für Wochentag (Montag), wenn der berechnete Tag auf Samstag oder Sonntag fällt
 X - steht für 'keine Korrektur'
 
4. Steuerung der Datumsberechnung (optional)

 - - das Zeichen "-" ist das Abbruchszeichen. Nach einmaliger Berechnung des neuen Datums 
     wird die Regel gelöscht.
 ! - das Zeichen "!" ist das Zeichen zum Erzwingen eines neuen Datums, obwohl ein Datum in
     dem Wiedervorlagefeld steht und das Wiedervorlagedatum in der Zukunft liegt
 * - das Zeichen "*" verhindert das Berechnen eines Datums, wobei "*" aus der Regel 
     gelöscht wird. Notwendig für das Plugin Redmine Attribute-Quickies
     
Beispiel: W1F - eine Woche weiter, erster Tag, also Montag
Beispiel: M3M - drei Monate ab heute, mittiger Tag, also der 15. des Monats
Beispiel: q1F- - nächstes Quartal, erster Tag des Quartals, also der 1. Jan., Apr., Jul. 
                oder Okt., nach einmaliger Berechnung wird die Regel gelöscht 
                (Einmalvorlage)               
Beispiel: D1- - morgen, dann Regel löschen
Beispiel: D1-! - morgen!, auch wenn ein anderes Wiedervorlage-Datum bereits notiert ist

Es wird stets ein Datum in der Zukuft berechnet, niemals in der Vergangenheit.
So würde für W0F an einem Freitag (W0 - diese Woche oder 0 Wochen weiter, Montag)
ein Tag in der Vergangenheit berechnet. In diesem Fall wird der nächste Montag berechnet.
So würde für für q0M (q0 - dieses Quartal oder 0 Quartale weiter) die Mitte des Quartals
berechnet, wenn das Quartal fast verstrichen ist. In diesem Fall wird das entsprechende
Datum im nächsten Quartal berechnet.
</pre>

app/views/redmine_auto_resubmission/help/_help_rule_field_en.html.erb
<h3>Field for resubmission-rule</h3>

<p>This custom field should be a text field or a drop-down-list for a predetermined 
<strong>resubmission-rule</strong> for calculation of a new resubmission date, which is 
calculated whenever a current resubmission-date lies in the past.</p>

<p>
<strong>Proposed values: &lt;rule&gt; &lt;decscriptive text&gt;</strong><br />

D1! tomorrow!<br />
W01! monday!<br />
W1X wöchentlich<br />
W2X biweekly<br />
W3X triweekly<br />
M1X monthly<br />
M1F monthly on the 1st<br />
M1M monthly on the 15th<br />
M2L monthly on last day of month<br />
M2X bimonthly<br />
M2F bimonthly on the 1st<br />
M2M bimonthly on the 15th<br />
M2L bimonthly on last day of month<br />
M3X trimonthly<br />
M3F trimonthly on the 1st<br />
M3M trimonthly on the 15th<br />
M3L trimonthly on last day of month<br />
M6X twice-a-year<br />
M6F on the 1st<br />
M6L on last day of month<br />
M12X yearly
</p>

<p>
The syntax of the resubmission-rule consists of three to four parameters: 
</p>

<pre>
1. parameter: epoch-identifier (necessary)

 D - stands for _D_ays
 W - stands for _W_eeks
 m - stands for _m_ondays
 M - stands for _M_onths
 q - stands for _q_uarters
 Y - stands for _Y_ears

2. parameter: integer (necessary)

 n - stands for the number of epochs
 
3. position of day within epoch 

 F - stands for _F_irst day of epoch, like first day of month, monday, first day of 
     quarter, or January 1st
 M - stands for _M_id of epoch, like 15th day of month, wednesday, 15th of 
     mid-of-quarter or June 30th
 L - stands for _L_ast of epoch, like last day of month, friday (last working day),
     last day of quarter or December 31st
 W - stands for _W_eekday (Monday), if calculated day falls on a Saturday or Sunday
 X - stands for no correction

3. control of date calculation

 - - the sign "-" is a killswitch. After one date calculation the resubmission rule is 
     deleted, so no further resubmissions happen
 ! - the sign "!" is a force sign to force date calculation even if a resubmission date
     present
 * - the sign "*" is a mock switch. The mock-switch is deleted from the resubmission-rule
     and no resubmission-date is calculated. Needed for Redmine Attribute-Quickie plugin
     
Example: W1F - one week further, first day, so monday 
Example: M3M - three months further from today, mid-day, so 15th of month
Example: q1- - next quarter, first day of quarter, so 1st Jan., Apr., Jul. or Oct., after
               one calculation further calculations are stopped, riule is deleted.
Example: D1- - tomorrow, then delete rule 
Example: D1-! - tomorrow!, even if a resubmission-date is present in the 
               resubmission-date-field
               
Resubmission dates are always calculated for the future, never for the past. 
So W0F would calculate "next monday"", if calculated on a friday, though W0 stands for 
this week (W0 zero weeks further, first day, monday) and would calculate last monday. 
In this case, the calculated date is advanced monday further into the future.
So q0M would calculate "next quarter mid-term" if calculated near to lapse of current 
quarter. In this case the calculated date is advanced one quarter into the future.
 
</pre>

app/views/redmine_auto_resubmission/help/_help_start_date_rule_field_de.html.erb
<h3>Feld für Startdatum-Regel</h3>

<p>Dieses benutzerdefinierte Feld sollte ein Text-Feld oder eine Drop-Down-Liste für 
ausgewählte <strong>Startdatum-Regeln</strong> zum Berechnen eines neuen 
Startdatums sein, das immer dann berechnet wird, wenn das aktuelle 
Startdatum in der Vergangenheit liegt.</p>

<p>Dieses Feld kann unkonfiguriert bleiben, um diese Funktion zu deaktivieren</p> 

app/views/redmine_auto_resubmission/help/_help_start_date_rule_field_en.html.erb
<h3>Field for start date rule</h3>

<p>This custom field should be a text field or a drop-down list field for selected 
<strong>start date rules</strong> to calculate a new due date, which is calculated 
if the current start date is a past date</p>

<p>This field may be left unconfigured to deactivate this function</p>

app/views/redmine_auto_resubmission/help/_help_status_id_field_de.html.erb
<h3>Status bei Wiedervorlage</h3>

<p>Dieses Feld bestimmt, welchen Status das Ticket bei Wiedervorlage erhält.</p>

app/views/redmine_auto_resubmission/help/_help_status_id_field_en.html.erb
<h3>Status at resubmission</h3>

<p>The contents of this field determines the status, the issue is set to at resubmission.</p>

app/views/redmine_auto_resubmission/help/_help_text_field_de.html.erb
<h3>Text für Wiedervorlage</h3>

<p>Der angegebene Text wird bei Wiedervoralge als Journal-Eintrag zur Dokumentation in das Ticket geschrieben.</p>
<p>Die Zeichenfolge '##' (ohne Anführungszeichen) wird durch den Namen des aktuellen Users ersetzt.</p>

app/views/redmine_auto_resubmission/help/_help_text_field_en.html.erb
<h3>Text for resubmission</h3>

<p>The provided text is written as a journal-entry into the issue at resubmission.</p>
<p>The string '##' (without quotation marks) is replaced by the name of the current user.</p>

app/views/resubmissions/_test_result.html.erb
<div class='flash notice'>
  <p>
    <label><%= l(:label_resubmission_date)     %></label>
      <span style="line-height:24px;"><%= @new_date.present? ? I18n.localize(@new_date, :format => :datemacro ) : '&nbsp;' %></span>
  </p>
  <p>
    <label><%= l(:label_new_resubmission_rule) %></label>
      <span style="line-height:24px;"><%= @new_rule.present? ? @new_rule : '&nbsp;' %></span>
  </p>
</div>

app/views/resubmissions/test_resubmission_rule.js.erb
$('#<%= escape_javascript @feedback_tag %>').html('<%= escape_javascript render "/resubmissions/test_result" %>');
$('input#startdate').val('<%= "#{@new_date ? @new_date.strftime("%F") : "" }" %>');
$('input#rule').val('<%= @new_rule %>');